### ISSUE TITLE
mv3 build 1.22.55 - no ability to save any page(s) with Iron or Edge browsers

### ISSUE THREAD

**Issue by FredThompsonII** [gildas-lormeau/SingleFile-MV3#18]
**Describe the bug**

The menu for mv3 build 1.22.55 in both Iron and Edge has no options to save pages. Forced update and lack of previous versions on chromewebstore render this add-on useless.

**Comment by gildas-lormeau** [comment]
I'm sorry but you could blame Microsoft and Google who is forcing us to migrate to MV3, especially since they decided to warn all the users about this issue.

**Comment by gildas-lormeau** [comment]
I cannot reproduce this issue actually.

**Comment by gildas-lormeau** [comment]
I guess you were referring to the menu of the icon. This will be fixed in the next version.
