### ISSUE TITLE
Brave 1.69.168 Chromium: 128.0.6613.138 (64)

### ISSUE THREAD

**Issue by cmhdream** [gildas-lormeau/SingleFile-MV3#25]
Unable to scrape title to name archive

**Comment by gildas-lormeau** [comment]
Can you please give more details about the issue?

**Comment by cmhdream** [comment]
https://github.com/user-attachments/assets/99a8111d-3355-472f-b057-946a9bb2e35b
![擴充功能 - SingleFile - 09-17_084411](https://github.com/user-attachments/assets/dd1e3a7a-822b-4b1e-8208-37301dcf0c3e)

**Comment by gildas-lormeau** [comment]
This is a known issue in Chomium-based browsers, see https://github.com/gildas-lormeau/SingleFile?tab=readme-ov-file#known-issues.

If the file name of a saved page looks like "56833935-156b-4d8c-a00f-19599c6513d3.html", disable the option "Misc > save pages in background". Reinstalling the browser may also fix this issue. You can find more info about this bug [here](https://bugs.chromium.org/p/chromium/issues/detail?id=892133).
