### ISSUE TITLE
Rest Form API Feature : Body content is mapped to 

### ISSUE THREAD

**Issue by yooper** [gildas-lormeau/SingleFile-MV3#26]
**Describe the bug**
When the data gets posted to the REST endpoint, its fields are not properly mapped.

**To Reproduce**
Setup a REST Form API destination endpoint

- URL : https//example.com
- autorization token : ''
- archive data field name : file
- archive URL field name : url

1. Open up the service worker with dev tools. Examine the network tab. 
2. Save a page with single file.
3. Examine the requests in the network tab that go to `https//example.com`

**Expected behavior**
The url field should be the url of the web page that was saved, not the body of the web page.

**Screenshots**
![image](https://github.com/user-attachments/assets/d29b0208-a000-40c0-a71c-af521d0dee68)

**Environment**
 - OS: Windows 11 
 - Browser: Chrome
 - Version: Latest

**Additional context**
I can look into the issue if you do not have time.

**Comment by gildas-lormeau** [comment]
Thanks, it was probably due to a bad copy-paste of the code between the MV2 and MV3 versions. The bug has been corrected, and the fix will be available in the next version.

**Comment by yooper** [comment]
Just wanted to confirm the fix works. Thank you.

**Comment by gildas-lormeau** [comment]
Thank you for the feedback!
