### ISSUE TITLE
Single File crashes Brave Browser 1.79 when saving page.

### ISSUE THREAD

**Issue by mario-grgic** [gildas-lormeau/SingleFile-MV3#27]
**Describe the bug**

I am on macOS 10.15 Sequoia and using Single File extension version 1.22.69 with Brave Browser Version 1.70.117 Chromium: 129.0.6668.59 (Official Build) (arm64)

Open any web page and then right click and select `SingleFile/Annotate and Save page..`. Attempt to save the page and Brave Browser application exits. On next startup Brave says it didn't exit normally and restores the previous browser session.

**Environment**
 - OS: macOS 15.0 (24A335)
 - Browser: Brave Browser Version 1.70.117 Chromium: 129.0.6668.59 (Official Build) (arm64)
 - Version: 1.22.69

**Comment by Pantarou1** [comment]
I also have this Issue now on Windows 11. Upon saving a Tab it goes through steps 1/3 , 2/3 and then just as the save part should show up the Brave-Browser crashes and closes.Upon restarting Brave tells me it didn't exit normally. Restoring the Page or not didn't change the outcome.I've closed every tab i had open , restarted the PC, cleared the Browser Cache and reinstalled SingleFile to no avail.I hope this can be resolved, I'm using Single-File daily and depend on it's Saving feature.

**Comment by dmryoz** [comment]
I have same issue both on MacOS 14.5 and Win10

**Comment by gildas-lormeau** [comment]
I'll look into it, but at first glance, it's a bug in Brave. As a general rule, if an extension crashes a browser, it's a browser bug. It seems that some other extensions suffer from the same problem, cf.:
 - https://community.brave.com/t/the-brave-browser-starts-and-immediately-crashes-due-to-a-number-of-errors-related-to-extensions/569472
 - https://community.brave.com/t/save-image-as-png-extensions-cause-brave-to-crash/569782

**Comment by gildas-lormeau** [comment]
I confirm I was able to reproduce the issue after updating Brave. You can circumvent it by disabling the option `Misc. > save pages in background` in SingleFile.

**Comment by gildas-lormeau** [comment]
Issue in the repository of Brave: https://github.com/brave/brave-browser/issues/41179

**Comment by mario-grgic** [comment]
@gildas-lormeau Thank you for doing the investigation and posting the ticked in Brave repo. The workaround you suggested also works.

**Comment by Pantarou1** [comment]
@gildas-lormeau Thank you very much for looking into this. Your workaround works fine , and since it mentions that "Save as ..." will remember the last saved directory by disabling the background-saving, i will actually use this going forward since i wanted this behaviour anyway. Thumbs up !

**Comment by MagnetoPause** [comment]
Experiencing same issue. It appears a similar extension "Save Page WE" seems to be working in Brave without crashing it.

**Comment by MagnetoPause** [comment]
> I confirm I was able to reproduce the issue after updating Brave. You can circumvent it by disabling the option `Misc. > save pages in background` in SingleFile.

Thanks, this works!

**Comment by gildas-lormeau** [comment]
Thank you very much for the info and the quick fix @iefremov!

**Comment by Pantarou1** [comment]
Thank you !

**Comment by mario-grgic** [comment]
This is now fixed.
