### ISSUE TITLE
Can singlefile save images locally?

### ISSUE THREAD

**Issue by HppZ** [gildas-lormeau/SingleFile-MV3#33]

**Comment by gildas-lormeau** [comment]
Yes and no, SingleFile can produce ZIP files instead of HTML pages. Thus, you just have to unzip the file to get the images, see the section "File format" in the options page for more info.

**Comment by HppZ** [comment]
I need html pages produced by singlefile to use local images instead of online images so that I can view that html pages offline.

**Comment by gildas-lormeau** [comment]
This is what SingleFile does. Images are always stored in the saved file (HTML or ZIP).

**Comment by HppZ** [comment]
nice job! thank you!
